In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense
import pandas as pd
import numpy as np

In [2]:
#Load data set
modeling = pd.read_csv("/home/disha/Documents/Project/ANN/Churn_Modelling.csv")
len(modeling)


10000

In [4]:
modeling.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [5]:
X = modeling.drop(labels=['RowNumber','CustomerId','Surname','Exited'],axis=1)
y = modeling['Exited']


In [6]:
X.head(10)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   
5          645     Spain    Male   44       8  113755.78              2   
6          822    France    Male   50       7       0.00              2   
7          376   Germany  Female   29       4  115046.74              4   
8          501    France    Male   44       4  142051.07              2   
9          684    France    Male   27       2  134603.88              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10  
5          1               0        149756.71  
6          1               1         10062.80  
7          1               0        119346.88  
8          0               1         74940.50  
9          1               1         71725.73

In [7]:
y.head(10)

0    1
1    0
2    1
3    0
4    0
5    1
6    0
7    1
8    0
9    0
Name: Exited, dtype: int64

In [8]:
#Convert Categorical Data into Numerical Data
from sklearn.preprocessing import LabelEncoder

In [9]:
label = LabelEncoder()
X['Geography'] = label.fit_transform(X['Geography'])


In [10]:
X.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0  Female   42       2       0.00              1   
1          608          2  Female   41       1   83807.86              1   
2          502          0  Female   42       8  159660.80              3   
3          699          0  Female   39       1       0.00              2   
4          850          2  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [11]:
label1 = LabelEncoder()
X['Gender'] = label1.fit_transform(X['Gender'])

In [12]:
X.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [13]:
X = pd.get_dummies(X,drop_first=True,columns=['Geography'])

In [14]:
X.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_1  Geography_2  
0               1        101348.88            0            0  
1               1        112542.58            0            1  
2               0        113931.57            0            0  
3               0         93826.63            0            0  
4               1         79084.10            0            1

In [15]:
#Feature Standardization

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.4,random_state= 0)

In [18]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [19]:
X_train

array([[-0.74443184,  0.9189403 ,  0.40072902, ...,  1.70272565,
        -0.57016519,  1.74758521],
       [ 0.00944062, -1.08820997,  0.11199624, ...,  0.42234916,
        -0.57016519,  1.74758521],
       [ 0.00944062,  0.9189403 , -0.17673654, ..., -0.5443884 ,
        -0.57016519,  1.74758521],
       ...,
       [ 0.89756434,  0.9189403 , -0.36922506, ...,  1.40847039,
        -0.57016519, -0.57221816],
       [-0.63083462, -1.08820997, -0.08049228, ...,  0.84189641,
        -0.57016519,  1.74758521],
       [-0.29004296, -1.08820997,  0.88195032, ...,  0.32360318,
         1.75387769, -0.57221816]])

In [20]:
#Bulid ANN
model = Sequential()
model.add(Dense(X.shape[1],activation = 'relu',input_dim = X.shape[1]))
model.add(Dense(128,activation='relu'))
model.add(Dense(1,activation='sigmoid'))



In [21]:
X.shape[1]

11

In [22]:
model.compile(optimize='adam',loss='binary_crossentropy',metric=['accuracy'])

In [23]:
#model fitting
model.fit(X_train,y_train.to_numpy(),batch_size=10,epochs=10,verbose=1)

Train on 6000 samples
Epoch 1/10
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
6000/6000 [==============================] - 4s 601us/sample - loss: 0.4575
Epoch 2/10
6000/6000 [==============================] - 2s 255us/sample - loss: 0.4157
Epoch 3/10
6000/6000 [==============================] - 2s 250us/sample - loss: 0.3894
Epoch 4/10
6000/6000 [==============================] - 2s 253us/sample - loss: 0.3711
Epoch 5/10
6000/6000 [==============================] - 2s 268us/sample - loss: 0.3620
Epoch 6/10
6000/6000 [==============================] - 2s 259us/sample - loss: 0.3542
Epoch 7/10
6000/6000 [==============================] - 1s 247us/sample - loss: 0.3515
Epoch 8/10
6000/6000 [==============================] - 2s 257us/sample - loss: 0.3483
Epoch 9/10
6000/6000 [==============================] - 1s 247us/sample - loss: 0.3462
Epoch 10/10
6000/6000 [==============================] - 2s 259us/sample - loss: 0.3435


In [25]:
#Predict the classes
y_pred = model.predict_classes(X_test)


In [26]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [27]:
y_test

9394    0
898     1
2398    0
5906    0
2343    0
       ..
4758    0
9914    0
7067    0
4578    0
4202    0
Name: Exited, Length: 4000, dtype: int64

In [29]:
X_test

array([[-0.55854548, -1.08820997, -0.36922506, ...,  1.60650951,
         1.75387769, -0.57221816],
       [-1.32274496, -1.08820997,  0.11199624, ...,  0.49431961,
        -0.57016519, -0.57221816],
       [ 0.5670997 , -1.08820997,  0.30448476, ..., -0.42402815,
        -0.57016519,  1.74758521],
       ...,
       [ 0.9801805 , -1.08820997, -1.42791192, ..., -0.1054965 ,
        -0.57016519, -0.57221816],
       [ 0.4121944 ,  0.9189403 , -0.08049228, ..., -0.962846  ,
        -0.57016519, -0.57221816],
       [-1.2917639 ,  0.9189403 , -0.85044636, ...,  0.01396845,
        -0.57016519, -0.57221816]])

In [32]:
model.evaluate(X_test,y_test.to_numpy())

4000/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

0.36013811457157135

In [33]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [35]:
confusion_matrix(y_test,y_pred)

array([[2969,  203],
       [ 394,  434]])

In [36]:
accuracy_score(y_test,y_pred)

0.85075